Group_id and groups type
oasis-tcs/csaf pull request #58
Opened 2020-06-22 19:57 UTC by tschmidtb51

- resolves #57 
- add "group_id_t" and "groups_t"
- refactor to use new types
- add generic keywords for documentation

2020-06-23 20:09 UTC, santosomar approved these changes

2020-06-24 15:58 UTC, sthagen approved these changes

2020-06-24 17:36 UTC, tolim approved these changes

2020-06-24 18:11 UTC, santosomar commented on csaf_2.0/json_schema/csaf_json_schema.json
> +    "group_id_t": {
During the June 24, 2020 monthly meeting, it was suggested and discussed to rename to `product_group_id_t` to make relationship to products explicit, as stated by @tolim above. The TC decided that this is the right approached (i.e., rename to `product_group_id_t`).

2020-06-24 18:11 UTC, santosomar requested changes
During the June 24, 2020 monthly meeting, it was suggested and discussed to rename to product_group_id_t to make relationship to products explicit, as stated by @tolim above. The TC decided that this is the right approached (i.e., rename to product_group_id_t).

2020-06-24 18:38 UTC, tschmidtb51 commented on csaf_2.0/json_schema/csaf_json_schema.json
> +    "groups_t": {
Addressed in [https://github.com/oasis-tcs/csaf/pull/58/commits/2a61d238696fd2747ea678081a7fedf4a4010830](https://github.com/oasis-tcs/csaf/pull/58/commits/2a61d238696fd2747ea678081a7fedf4a4010830).

2020-06-24 18:39 UTC, tschmidtb51 commented on csaf_2.0/json_schema/csaf_json_schema.json
> +    "group_id_t": {
Addressed in [https://github.com/oasis-tcs/csaf/pull/58/commits/2a61d238696fd2747ea678081a7fedf4a4010830](https://github.com/oasis-tcs/csaf/pull/58/commits/2a61d238696fd2747ea678081a7fedf4a4010830)

2020-06-24 19:47 UTC, santosomar approved these changes
Thank you for taking care of this so quickly.

2020-06-24 19:47 UTC, merged

2020-06-25 06:56 UTC, sthagen commented on csaf_2.0/json_schema/csaf_json_schema.json
> +                  "$ref": "#/definitions/product_groups_t"
:+1: