2024-06-26 meeting minutes
oasis-tcs/csaf pull request #760
Opened 2024-07-31 13:35 UTC by santosomar

Meeting minutes for the CSAF TC monthly call hosted on 2024-06-26.

2024-07-31 15:35 UTC, sthagen approved these changes
I guess the note taker was not me but besides this I do not object merge.

2024-07-31 15:35 UTC, sthagen commented on meeting_minutes/2024/2024-06-26.md
> +| Stefan     | Hagen       | Individual                                                  | Voting Member, taking notes |
Did I really take notes? Not so sure ...

2024-07-31 20:40 UTC, tschmidtb51 requested changes
Thank you for taking note. Some comments below

2024-07-31 20:40 UTC, tschmidtb51 commented on meeting_minutes/2024/2024-06-26.md
> +  - Thomas Schmidt 6/26/2024 1:25 PM • oasis-csaf@connectedcommunity.org
```suggestion

2024-07-31 20:40 UTC, tschmidtb51 commented on meeting_minutes/2024/2024-06-26.md
> +    I'll raise it on GitHub for discussion next time - If CVE's are to be assigned for Cloud/AI/ML regardless of the need for action by the customer, we might need to distinguish between CVE's requir
```suggestion
  - Vivek Nair: Have we looked at the [new CNA rules](https://www.cve.org/Media/News/item/blog/2024/05/07/CNA-Rules-v4-0-Update-and-Transition) and its impact on CSAF?
    - will raise it on GitHub for discussion next time - If CVE's are to be assigned for Cloud/AI/ML regardless of the need for action by the customer, we might need to distinguish between CVE's requiring action vs those which do not (like, maybe by a flag?).

2024-07-31 20:40 UTC, tschmidtb51 commented on meeting_minutes/2024/2024-06-26.md
> +  - Covered by CSAF aggregators? Is that their purpose.  They collect who they are publishing, CSAF may not be compliant, but can’t retrieve automatically.
```suggestion
  - Covered by CSAF aggregators? Is that their purpose. They decide who they are collecting. CSAF publishers may be compliant, but can’t retrieve automatically (and therefore hard to find).

2024-07-31 20:40 UTC, tschmidtb51 commented on meeting_minutes/2024/2024-06-26.md
> +  - Discuss more at next meeting.
```suggestion
 - Sonny van Lingen: And at least theoretically one could run a CSAF Trusted Provider with `"list_on_csaf_aggregators": "false"` and `"mirror_on_csaf_aggregators": "false"` :-)
 - Value to have a list but who would collect and maintain. Include in CSAF 2.1 field to announce it.
  - Martin Prpic (Red Hat): Could just start collecting vendor names in that issue and then convert it into a list for the website.
  - Can collect names and find way to convert it over. Promote data quality throughout system.
  - Thomas Schmidt: starting points could be [CSAF lister](https://wid.cert-bund.de/.well-known/csaf-aggregator/aggregator.json) and [CSAF aggregator](https://aggregator.cert-bund.de/.well-known/csaf-aggregator/aggregator.json) of BSI
  - Discuss more at next meeting.

2024-07-31 20:40 UTC, tschmidtb51 commented on meeting_minutes/2024/2024-06-26.md
> +  - CSAF aggregator: aggregator.cert-bund.de/.well-known/csaf-aggregator/aggregator.json
They belong to the topic #686 above.
```suggestion

2024-07-31 20:40 UTC, tschmidtb51 commented on meeting_minutes/2024/2024-06-26.md
> +- The meeting was adjourned @ 18:058 UTC
```suggestion
- The meeting was adjourned @ 17:58 UTC

2024-07-31 20:40 UTC, tschmidtb51 commented on meeting_minutes/2024/2024-06-26.md
> +**Note**: All monthly meetings take place on the last Wednesday of each month at 18:00 UTC (19:00 CET, 13:00 EST, 10:00 PST).
As the time is always the same (except for the European/US daylight saving shift weeks), I think we are meeting according to ET...
```suggestion
**Note**: All monthly meetings take place on the last Wednesday of each month at 13:00 ET (19:00 CEST/19:00 CET, 10:00 PT, 17:00/18:00 UTC).

2024-08-25 18:21 UTC, santosomar commented
I believe that I captured all of your suggestions @tschmidtb51  in the current commits. Please check.

2024-08-26 13:37 UTC, tschmidtb51 reviewed
@santosomar Sorry - looks like I missed some things in my first review

2024-08-26 13:37 UTC, tschmidtb51 commented on meeting_minutes/2024/2024-06-26.md
> +  - Call for action via email Thomas Schimdt to send out.
```suggestion
- Call for action via email Thomas Schmidt to send out.

2024-08-26 13:37 UTC, tschmidtb51 commented on meeting_minutes/2024/2024-06-26.md
> +- Issue – Enforce product_version_range rules #636 (presented by Thomas Schmidt)
```suggestion
- Issue – Enforce `product_version_range` rules #636 (presented by Thomas Schmidt)

2024-08-26 13:37 UTC, tschmidtb51 commented on meeting_minutes/2024/2024-06-26.md
> +  - Will work with Martin offline Thomas Schmidt to make it more feasible.
```suggestion
  - Thomas Schmidt will work with Martin offline to make it more feasible.

2024-08-26 13:37 UTC, tschmidtb51 commented on meeting_minutes/2024/2024-06-26.md
> + - Value to have a list but who would collect and maintain. Include in CSAF 2.1 field to announce it.
```suggestion
  - Sonny van Lingen: And at least theoretically one could run a CSAF Trusted Provider with `"list_on_csaf_aggregators": "false"` and `"mirror_on_csaf_aggregators": "false"` :-)
  - Value to have a list but who would collect and maintain. Include in CSAF 2.1 field to announce it.

2024-08-27 05:33 UTC, sthagen commented
Let us not make these minutes too beautiful 🙈 ... LGTM, still.

2024-08-27 08:46 UTC, tschmidtb51 approved these changes
LGTM

2024-08-28 04:49 UTC, santosomar commented
Motion for approval at: https://groups.oasis-open.org/discussion/motion-to-approve-csaf-june-2024-meeting-minutes

2024-09-24 15:49 UTC, tschmidtb51 commented
Motion moved and seconded: https://groups.oasis-open.org/discussion/motion-to-approve-csaf-june-2024-meeting-minutes

2024-09-24 15:49 UTC, merged