ASCII armored OpenPGP
oasis-tcs/csaf pull request #829
Opened 2024-11-18 23:48 UTC by tschmidtb51

- resolves oasis-tcs/csaf#797
- add explicit statements about OpenPGP signatures and key files being ASCII armored

2024-11-18 23:49 UTC, tschmidtb51 commented
@bernhardreiter Please review

2024-11-20 11:05 UTC, sthagen approved these changes
LGTM.

2024-11-20 11:29 UTC, bernhardreiter requested changes
'MAY' would still allow using binary files, which is in contrast how I have understood the following conclusion: https://github.com/oasis-tcs/csaf/issues/797#issuecomment-2484394996

2024-11-20 13:54 UTC, tschmidtb51 commented on csaf_2.1/prose/edit/src/distributing.md
> +This signature SHALL be presented as an ASCII armored file.
> `SHALL` leaves room for deviation for a good reason.

I think you might have confound `SHALL` and `SHOULD`. :thinking:

2024-11-20 13:55 UTC, tschmidtb51 commented on csaf_2.1/prose/edit/src/distributing.md
> +This key file SHALL be presented as an ASCII armored file.
See above.

2024-11-21 15:23 UTC, bernhardreiter commented on csaf_2.1/prose/edit/src/distributing.md
> +This signature SHALL be presented as an ASCII armored file.
Indeed. 🙊  Sorry for the noise.

2024-11-21 19:42 UTC, sthagen commented on csaf_2.1/prose/edit/src/distributing.md
> +This signature SHALL be presented as an ASCII armored file.
Well, I think we focus on the producer, then the SHALL is in fact a hard requirement (on the producer and not the file in isolation in some controlled place, no "drift wood").

2024-11-21 23:14 UTC, tschmidtb51 commented
Pending motion: https://groups.oasis-open.org/discussion/motion-for-779

2024-11-27 03:14 UTC, merged